
# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir:
  base: Users/alessiobocco/Documents/Data_Science/Data_Challenges/DesafioAgTech2020
  lib: Users/alessiobocco/sissa/src/R/lib
  input: ./dataset
  output: ./resultado
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Cantidad maxima de procesos paralelos
# ------------------------------------------------------------------------------
max.procesos: 6
# ------------------------------------------------------------------------------
